server:
  port: 3000

spring:
  datasource:
    url: jdbc:h2:~/.h2/nirdeca-accounting;AUTO_SERVER=TRUE;FILE_LOCK=FILE;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate